CREATE TABLE IF NOT EXISTS data ( 
    name varchar(255),
    price varchar(255),
    image varchar(255),
    category varchar(255),
    type varchar(255),
    description JSON
);

ALTER TABLE data ADD UNIQUE(name);


INSERT INTO data VALUES
('Adaptateur Smart Things - HD2018GH','39,00 €','/assets/image/1.jpg','Samsung','Accessory',JSON_ARRAY("Contrôle à distance")),
('Coque en silicone pour S20 FE | FE 5G','39,90 €','/assets/image/8.jpg','Samsung','Accessory',JSON_ARRAY("Protection contre les chocs et les rayures","Finition douce offrant une bonne prise en main")),
('Étui en aramide pour Galaxy Z Fold2 5G','74,90 €','/assets/image/9.jpg','Samsung','Accessory',JSON_ARRAY("Design renforcé","2 angles de visualisation","Ultra fin et léger","Toucher agréable")),
('Étui en cuir pour Galaxy Z Fold2 5G','99,90 €','/assets/image/10.jpg','Samsung','Accessory',JSON_ARRAY("Finition cuir","Bonne prise en main","Protection contre les chocs et rayures","Doublure fine et protectrice à l''intérieur")),
('Galaxy Watch3 Bluetooth (45mm)','659,00 €','/assets/image/11.jpeg','Samsung','Smartwatch',JSON_ARRAY("Design affirmé avec lunette rotative","Personnalisation bracelet et cadran","Sport & bien-être","Étanche jusqu’à 50m")),
('Galaxy Watch3 4G (45mm)','509,00 €','/assets/image/5.jpeg','Samsung','Smartwatch',JSON_ARRAY("Design affirmé avec lunette rotative","Personnalisation bracelet et cadran","Sport & bien-être","Étanche jusqu’à 50m")),
('Galaxy Watch3 Bluetooth (41mm)','429,00 €','/assets/image/6.jpg','Samsung','Smartwatch',JSON_ARRAY("Design affirmé avec lunette rotative","Personnalisation bracelet et cadran","Sport & bien-être","Étanche jusqu’à 50m")),
('Galaxy Watch 46 mm eSIM 4G ','329,00 €','/assets/image/7.jpeg','Samsung','Smartwatch',JSON_ARRAY("Design soigné avec lunette rotative","Connectivité cellulaire","Fonctionnalités sport et bien-être","Votre musique vous suit partout")),
('USB 3.0 Flash Drive DUO ','29,00 €','/assets/image/1.jpg','Samsung','Informatic',JSON_ARRAY("Une vitesse de transfert allant jusqu’à 130MB/s","Se connecte aux Smartphones, tablets et PC par micro USB","Protection à 5 niveaux")),
('USB 3.0 Flash Drive FIT ','15,00 €','/assets/image/2.jpg','Samsung','Informatic',JSON_ARRAY("Une vitesse de transfert allant jusqu’à 130MB/s","Se connecte aux netbooks et PC ultra fins","Protection à 5 niveaux")),
('USB 3.0 Flash Drive BAR ','20,00 €','/assets/image/3.jpg','Samsung','Informatic',JSON_ARRAY("Une vitesse de transfert allant jusqu’à 130MB/s","Design en métal haut de gamme","Protection à 5 niveaux")),
('Galaxy S20 FE','659,00 €','/assets/image/12.jpg','Samsung','Smartphone',JSON_ARRAY("Des photos lumineuses de jour et de nuit","Grand écran 6,5’’ ultra fluide 120Hz","Space Zoom 30x")),
('Galaxy A71','469,00 €','/assets/image/14.jpeg','Samsung','Smartphone',JSON_ARRAY("Ecran Infinity 6,7'''' Super AMOLED","Quadruple capteur photo - Mode Macro","Capteur principal 64 MP pour des photos nettes","Charge ultra rapide - Batterie longue durée - 4500")),
('Galaxy Z Fold2 5G','2020,00 €','/assets/image/13.jpg','Samsung','Smartphone',JSON_ARRAY("Grand écran pliable intérieur de 7,6''''","Ecran extérieur de 6,2''''","Charnière à position libre pour plus de flexibilité")),
('Galaxy A31','299,00 €','/assets/image/15.jpg','Samsung','Smartphone',JSON_ARRAY("Écran panoramique 6,4'''' Super AMOLED","Quadruple capteur photo avec Ultra grand angle","Batterie longue durée - 5000 mAh + Charge rapide","Stockage 64 Go + lecteur d''empreinte sous l''écran")),
('Galaxy Tab A7 4G','299,00 €','/assets/image/16.jpeg','Samsung','Tablet',JSON_ARRAY("Un grand écran de 10.4’’","Autonameie longue durée","Samsung Kids","Caméra en mode paysage pour vos appels vidéo")),
('Galaxy Tab S7 Wi-Fi','719,00 €','/assets/image/17.jpg','Samsung','Tablet',JSON_ARRAY("Écran ultra immersif 11’’","S Pen connecté ultra précis","La puissance d’un ordinateur","Stockage 128/256Go + port microSD")),
('Galaxy Tab S6 Lite','349,00 €','/assets/image/18.jpg','Samsung','Tablet',JSON_ARRAY("Design fin et finition en aluminum","S Pen amélioré pour une expérience plus ergonamei","Écran panoramique 10,4''''","Mémoire embarquée 64Go")),
('Galaxy Tab S6 Gris Titane 4G','679,00 €','/assets/image/19.jpg','Samsung','Tablet',JSON_ARRAY("Ultrafine 5,7mm","Écran panoramique 10,5’’","S Pen avec contrôle par gestes","Lecteur d’empreinte sous l’écran")),
('iPad Air','669,00 €','/assets/image/25.jpeg','Apple','Tablet',JSON_ARRAY("10,9″Écran Liquid Retina","Puce A14 Bionic","Compatible avec le Magic Keyboard et le Smart Keyboard Folio","Compatible avec l’Apple Pencil (2ᵉ génération)")),
('iPad Pro','899,00 €','/assets/image/24.jpeg','Apple','Tablet',JSON_ARRAY("12,9″ et 11″ Écran Liquid Retina avec ProMotion","Puce A12Z Bionic","Compatible avec le Magic Keyboard et le Smart Keyboard Folio","Compatible avec l’Apple Pencil (2ᵉ génération)")),
('iPad','389,00 €','/assets/image/26.jpeg','Apple','Tablet',JSON_ARRAY("10,2″Écran Retina","Puce A12 Bionic","Compatible avec le Smart Keyboard","Compatible avec l’Apple Pencil (1re génération)")),
('iPad mini','459,00 €','/assets/image/27.jpeg','Apple','Tablet',JSON_ARRAY("7,9″Écran Retina","Puce A12 Bionic","Compatible avec les claviers Bluetooth","Compatible avec l’Apple Pencil (1re génération)")),
('iPhone 11 Pro','1159,00 €','/assets/image/21.png','Apple','Smartphone',JSON_ARRAY("Triple appareil photo (ultra grand‑angle, grand‑angle, téléobjectif)","Jusqu’à 17 heures de lecture vidéo","Résistant à l’eau jusqu’à 2 mètres de profondeur pendant 30 minutes maximum","Écran Super Retina XDR 5,8″ ou 6,5″","Écran Liquid Retina HD 6,1″")),
('iPhone 11','809,00 €','/assets/image/22.png','Apple','Smartphone',JSON_ARRAY("Double appareil photo (ultra grand‑angle, grand‑angle)","Quadruple capteur photo - Mode Macro","Capteur principal 64 MP pour des photos nettes","Charge ultra rapide - Batterie longue durée - 4500")),
('iPhone X','709,00 €','/assets/image/23.png','Apple','Smartphone',JSON_ARRAY("Appareil photo(grand‑angle)","Jusqu’à 16 heures de lecture vidéo","Résistant à l’eau jusqu’à 1 mètre de profondeur pendant 30 minutes maximum","Écran Liquid Retina HD 6,1″")),
('iPhone SE','489,00 €','/assets/image/20.png','Apple','Smartphone',JSON_ARRAY("Appareil photo(grand‑angle)","Jusqu’à 13 heures de lecture vidéo","Résistant à l’eau jusqu’à 1 mètre de profondeur pendant 30 minutes maximum","Écran Retina HD 4,7″")),
('Apple Watch Series 6','429,00 €','/assets/image/36.jpeg','Apple','Smartwatch',JSON_ARRAY("Boîtier de 40 ou 44 mm","Écran Retina toujours activé","GPS + Cellular1 GPS","App Oxygène sanguin","App ECG","Notifications de fréquence cardiaque élevée ou faible Notifications d’arythmie","Configuration familiale prise en charge (modèles GPS + Cellular)","Résistance à l’eau jusqu’à 50 mètres")),
('Apple Watch SE','299 ,00 €','/assets/image/37.jpeg','Apple','Smartwatch',JSON_ARRAY("Boîtier de 40 ou 44 mm","Écran Retina ","GPS + Cellular1 GPS","Notifications de fréquence cardiaque élevée ou faible Notifications d’arythmie","Configuration familiale prise en charge (modèles GPS + Cellular)","Résistance à l’eau jusqu’à 50 mètres")),
('Apple Watch Series 3','219,00 €','/assets/image/38.jpeg','Apple','Smartwatch',JSON_ARRAY("Boîtier de 38 ou 42 mm","Écran Retina","GPS","Notifications de fréquence cardiaque élevée ou faible Notifications d’arythmie","Résistance à l’eau jusqu’à 50 mètres")),
('HomePod','329,00 €','/assets/image/35.jpeg','Apple','Accessory',JSON_ARRAY("Sans-fil,Bluetooth 5.0,Accès invité direct","Micro interne de calibration des fréquences basses pour une correction automatique des graves","Formation de faisceaux pour le son direct et ambiant")),
('HomePod mini','99,00 €','/assets/image/34.jpeg','Apple','Accessory',JSON_ARRAY("Son riche et ample","Assistant intelligent","Contrôle de votre maison connectée","Confidentialité et sécurité")),
('AirPods Pro','279,00 €','/assets/image/33.png','Apple','Accessory',JSON_ARRAY("Réduction active du bruit","Micro intérieur","Capteur-pression","Résistance à l’eau et à la transpiration","Boîtier de charge sans fil","Gravure personnalisée : initiales, emoji, etc.")),
('MacBook Air','1 199,00 €','/assets/image/31.jpeg','Apple','Informatic',JSON_ARRAY("Écran Retina 13,3 pouces","Jusqu’au processeur Intel Core i7 quadricœur","Jusqu’à 16 Go de mémoire","Jusqu’à 2 To de stockage","Jusqu’à 11 h d’autonameie","Touch ID","Magic Keyboard rétroéclairé")),
('MacBook Pro 13”','1 499 ,00 €','/assets/image/32.jpeg','Apple','Informatic',JSON_ARRAY("Écran Retina 13,3 pouces","Jusqu’au processeur Intel Core i7 quadricœur","Jusqu’à 32 Go de mémoire","Jusqu’à 4 To de stockage","Jusqu’à 10 h d’autonameie","Touch Bar et Touch ID","Magic Keyboard rétroéclairé")),
('MacBook Pro 16” ','2 699,00 €','/assets/image/30.jpeg','Apple','Informatic',JSON_ARRAY("Écran Retina 16pouces","Jusqu’au processeur Intel Core i9 8 cœurs","Jusqu’à 64 Go de mémoire","Jusqu’à 8 To de stockage","Jusqu’à 11 h d’autonameie","Touch Bar et Touch ID","Magic Keyboard rétroéclairé")),
('Huawei MatePad Pro','549,99 €','/assets/image/39.png','Huawei','Tablet',JSON_ARRAY("Écran Huawei FullView de 10,8 pouces","Processeur Kirin 990","Quadruple haut-parleur","Compatible Huawei Share, Mode PC, Clavier")),
('Huawei MediaPad M5 lite','229,99 €','/assets/image/40.png','Huawei','Tablet',JSON_ARRAY("Ecran 10,1'''' 1080p","Quatre haut-parleurs stéréo","Mode confort des yeux")),
('Huawei MediaPad M6 10.8”','349,99 €','/assets/image/41.jpg','Huawei','Tablet',JSON_ARRAY("Processeur Kirin 980","Ecran 2K","Quadruple haut-parleur Harman Kardon")),
('Huawei MediaPad M5 lite 8','149,00 €','/assets/image/41.png','Huawei','Tablet',JSON_ARRAY("Ecran 8.0” 283PPI","Quadruple haut-parleur Harman Kardon","Batterie de 5100 mAh")),
('Huawei P40 Pro+','1 199,99 €','/assets/image/42.png','Huawei','Smartphone',JSON_ARRAY("Quintuple capteur Ultra Vision conçu avec Leica","Zoom optique 10x, zoom max 100x","Ecran incurvé Overflow, IP68")),
('Huawei P30 Pro New Edition','659,99 €','/assets/image/44.png','Huawei','Smartphone',JSON_ARRAY("8 Go de RAM et 256 Go de stockage","Quadruple caméra SuperSensing conçue avec Leica","Zoom jusqu''à 50x")),
('Huawei P smart S','229,99 €','/assets/image/43.png','Huawei','Smartphone',JSON_ARRAY("Triple caméra dotée d''IA et capteur principal de 48 MP1","Stockage de 128 Go","Ecran OLED de 6,3''''")),
('Huawei P30 Pro','599,99 €','/assets/image/45.png','Huawei','Smartphone',JSON_ARRAY("Écran OLED de 6,47 pouces, IP68","Quadruple Caméra Leica, Zoom hybride 10x, Capteur SuperSpectrum","Technologie Huawei SuperCharge 40 W")),
('Huawei FreeBuds 3i','89,99 €','/assets/image/51.jpg','Huawei','Accessory',JSON_ARRAY("Payez en 3x ou 4x sans frais, disponible uniquement pour les commandes supérieures à 149 €","Réduction de bruit active","3 microphones pour une qualité d''appel exceptionnelle","Design intra-auriculaire avec 4 paires d''ambouts de différentes taille")),
('Huawei Sound X','269,99 €','/assets/image/50.png','Huawei','Accessory',JSON_ARRAY("Double Woofers Devialet","Architecture acoustique ''Push-Push'' de D","Technologie Huawei Share")),
('Huawei FreeBuds 3','129,99 €','/assets/image/49.png','Huawei','Accessory',JSON_ARRAY("Réduction active du bruit","Processeur Kirin A1, temps de latence ultr","Charge sans-fil, autonameie longue durée")),
('Huawei MateBook D 14 2020','599,99 €','/assets/image/48.png','Huawei','Informatic',JSON_ARRAY("Windows 10 Home","Ecran FullView de 14 pouces","Continuité multi-écrans")),
('Huawei MateBook 14 2020','1 049,99 €','/assets/image/47.png','Huawei','Informatic',JSON_ARRAY("Windows 10 Home","10ème Génération de processeurs Intel®Core™","Ecran Huawei FullView de 14 pouces")),
('Huawei MateBook X Pro 2020','1 299,99 €','/assets/image/46.png','Huawei','Informatic',JSON_ARRAY("Windows 10 Home","Écran FullView 3K","Huawei Share","10 ème Génération de processeurs Intel®","Jusqu’à 11 h d’autonameie"));