spring:
    application:
        name: "javaeeproject"

# Mysql
    datasource:
        driver-class-name: "com.mysql.cj.jdbc.Driver"
        url: "jdbc:mysql://localhost:3306/programmationAvancee"
        username: root
        password: 
        platform: mysql
        
    jpa:
        show-sql: true
        hibernate:
                  ddl-auto: create-drop
        properties:
                   hibernate:
                             dialect: "org.hibernate.dialect.MySQL5Dialect"
  
    profiles:
      active:
        - "dev"         
        


server:
  port: 8080