spring:
    application:
        name: javaeeproject
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/programmationAvancee?useSSL=false
        username: root
        password: root
        



server:
  port: 4200