GET http://localhost:8080/departments HTTP/1.1
content-type: application/json

###
GET http://localhost:8080/department/?dep=38


###
POST http://localhost:8080/department HTTP/1.1
content-type: application/json

{
    "numDep": "2A",
    "nomDep": "CORSE-DU-SUD",
    "chefLieu": "2A004"
  }
###
GET http://localhost:8080/lieux HTTP/1.1
content-type: application/json

###
GET http://localhost:8080/lieu/


###
POST http://localhost:8080/lieu HTTP/1.1
content-type: application/json

{
    "codeInsee": "30189",
    "nomCom": "NIMES",
    "longitude": "4.360054",
    "latitude": "43.836699",
    "dep": "30"
  }


###
PATCH http://localhost:8080/products/5f923332bb78d9238c5165f7 HTTP/1.1
content-type: application/json

[
  { "propName" : "type", "value": "Tablet"  }
]

# "propName" : "name", "value": "Amir"
# "propName" : "price", "value": "1100",
#     "propName" : "image", "value": "/assets/image/2.jpg",
#     "propName" : "category", "value": "Apple",
#     "propName" : "type", "value": "Smartphone",
#     "propName" : "description", "value": ["very Excelent phone", "Awsome","Smallll"]

###
DELETE http://localhost:8080/products/5f9413e0d3527b0fae4f4701 HTTP/1.1
content-type: application/json

###


POST http://localhost:8080/products
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

{
  "name"       : "Ali",
  "price"      : "34",
  "image"      : "/assets/image/1.jpeg",
  "category"   : "Apple",
  "type"       : "SmartWatch",
  "description": ["very Excelent phone", "Awsome","Big"]
}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.jpeg"
Content-Type: image/jpeg

< ./1.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###








# Orders
GET http://localhost:8080/orders/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Il9pZCI6IjVmOTYyNmY0OTNjM2U1MjhmZmI5Y2M1NyIsIm5hbWUiOiJBbWlyIFNISVJBTEkgUE9VUiIsImVtYWlsIjoiZW1hc2FsYXJpQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiZW1hIiwicGFzc3dvcmQiOiIkMmEkMTAkZm51L3FUdXp6Z2hONk1GOVNDWHlYLml3QUQ5YWhGdWlPaDA5cUVDS0lQYkMyZllHZ2ZDcFMiLCJfX3YiOjB9LCJpYXQiOjE2MDM2NzU5MzYsImV4cCI6MTYwNDI4MDczNn0.Z4VnOFMXBQGrq_0_SGzIjghsOEmefVxt1WTW1DWL5mQ

###
GET http://localhost:8080/orders/5f962fc233d3212a131f6654 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Il9pZCI6IjVmOTYyNmY0OTNjM2U1MjhmZmI5Y2M1NyIsIm5hbWUiOiJBbWlyIFNISVJBTEkgUE9VUiIsImVtYWlsIjoiZW1hc2FsYXJpQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiZW1hIiwicGFzc3dvcmQiOiIkMmEkMTAkZm51L3FUdXp6Z2hONk1GOVNDWHlYLml3QUQ5YWhGdWlPaDA5cUVDS0lQYkMyZllHZ2ZDcFMiLCJfX3YiOjB9LCJpYXQiOjE2MDM2NzU5MzYsImV4cCI6MTYwNDI4MDczNn0.Z4VnOFMXBQGrq_0_SGzIjghsOEmefVxt1WTW1DWL5mQ


###
PATCH http://localhost:8080/orders/amir HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjhjMGE4NjIxMzIyZDU4NzE2NzAxMzkiLCJuYW1lIjoiQW1pciBTSElSQUxJIFBPVVIiLCJlbWFpbCI6ImVtYXNhbGFyaUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImVtYSIsInBhc3N3b3JkIjoiJDJhJDEwJExSMm52UTgzSFFOZTFjQVNFbzVnUy5KSnA0d01GcTdxZ2NPdTBXSkt2QndQT09YOUdiQ1BhIiwiX192IjowLCJpYXQiOjE2MDMwNzgzODEsImV4cCI6MTYwMzY4MzE4MX0.fboKqI5-u8OkuBh56ulgDI1Z6gOahOVQOF5j7kh0umU

###
DELETE http://localhost:8080/orders/5f926dd45bfa7f2b5cab7906 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjhjMGE4NjIxMzIyZDU4NzE2NzAxMzkiLCJuYW1lIjoiQW1pciBTSElSQUxJIFBPVVIiLCJlbWFpbCI6ImVtYXNhbGFyaUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImVtYSIsInBhc3N3b3JkIjoiJDJhJDEwJExSMm52UTgzSFFOZTFjQVNFbzVnUy5KSnA0d01GcTdxZ2NPdTBXSkt2QndQT09YOUdiQ1BhIiwiX192IjowLCJpYXQiOjE2MDMwNzgzODEsImV4cCI6MTYwMzY4MzE4MX0.fboKqI5-u8OkuBh56ulgDI1Z6gOahOVQOF5j7kh0umU


###
POST http://localhost:8080/orders HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Il9pZCI6IjVmOTYyNmY0OTNjM2U1MjhmZmI5Y2M1NyIsIm5hbWUiOiJBbWlyIFNISVJBTEkgUE9VUiIsImVtYWlsIjoiZW1hc2FsYXJpQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiZW1hIiwicGFzc3dvcmQiOiIkMmEkMTAkZm51L3FUdXp6Z2hONk1GOVNDWHlYLml3QUQ5YWhGdWlPaDA5cUVDS0lQYkMyZllHZ2ZDcFMiLCJfX3YiOjB9LCJpYXQiOjE2MDM2NzU5MzYsImV4cCI6MTYwNDI4MDczNn0.Z4VnOFMXBQGrq_0_SGzIjghsOEmefVxt1WTW1DWL5mQ

{
  "quantity": "2",
  "product": "iPhone 12",
  "userId": "5f8e1de97f8f3d15035eff59"
}

###





# Users

GET http://localhost:8080/users/test

###


GET http://localhost:8080/users/profile HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjhjMGE4NjIxMzIyZDU4NzE2NzAxMzkiLCJuYW1lIjoiQW1pciBTSElSQUxJIFBPVVIiLCJlbWFpbCI6ImVtYXNhbGFyaUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImVtYSIsInBhc3N3b3JkIjoiJDJhJDEwJExSMm52UTgzSFFOZTFjQVNFbzVnUy5KSnA0d01GcTdxZ2NPdTBXSkt2QndQT09YOUdiQ1BhIiwiX192IjowLCJpYXQiOjE2MDMwNzgzODEsImV4cCI6MTYwMzY4MzE4MX0.fboKqI5-u8OkuBh56ulgDI1Z6gOahOVQOF5j7kh0umU

###
GET  http://localhost:8080/users/authenticate HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjhlMWRlOTdmOGYzZDE1MDM1ZWZmNTkiLCJuYW1lIjoiQW1pciIsImVtYWlsIjoiZW1hc2FsYXJpQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiYW1pciIsInBhc3N3b3JkIjoiJDJhJDEwJGJrYXdSNnBCRE5kTWlUVTRuN0UwbnUyQVdNQzB4ckMyeXVJamI4Q2htL0ZXN0Y3RWc4Tkd5IiwiX192IjowLCJpYXQiOjE2MDMxNTc1ODEsImV4cCI6MTYwMzc2MjM4MX0.fwaDnBtQozvMC_hOX540EFx-ruHZkrg1uqbE8ORoFQ4

{
  "username":"emasalari@gmail.com",
  "password":"123"
}

###
DELETE http://localhost:8080/users/5f8f972bdc12fb2c21181671 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjhlMWRlOTdmOGYzZDE1MDM1ZWZmNTkiLCJuYW1lIjoiQW1pciIsImVtYWlsIjoiZW1hc2FsYXJpQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiYW1pciIsInBhc3N3b3JkIjoiJDJhJDEwJGJrYXdSNnBCRE5kTWlUVTRuN0UwbnUyQVdNQzB4ckMyeXVJamI4Q2htL0ZXN0Y3RWc4Tkd5IiwiX192IjowLCJpYXQiOjE2MDMxNTc1ODEsImV4cCI6MTYwMzc2MjM4MX0.fwaDnBtQozvMC_hOX540EFx-ruHZkrg1uqbE8ORoFQ4

###








###
GET https://example.com/comments?page=2&pageSize=10


###
GET https://example.com/comments
    ?page=2
    &pageSize=10

###

POST https://example.com/comments HTTP/1.1
Content-Type: application/xml
Authorization: token xxx

<request>
    <name>sample</name>
    <time>Wed, 21 Oct 2015 18:27:50 GMT</time>
</request>


###
POST https://api.github.com/graphql
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

query ($name: String!, $owner: String!) {
  repository(name: $name, owner: $owner) {
    name
    fullName: nameWithOwner
    description
    diskUsage
    forkCount
    stargazers(first: 5) {
        totalCount
        nodes {
            login
            name
        }
    }
    watchers {
        totalCount
    }
  }
}

{
    "name": "vscode-restclient",
    "owner": "Huachao"
}


###
