GET http://localhost:8888

###

GET http://localhost:8888/categories

###
GET http://localhost:8888/categories/Samsung

###
GET http://localhost:8888/categories/Apple/Tablet

###





# annonces

GET http://localhost:8888/annonces HTTP/1.1
content-type: application/json

###
GET http://localhost:8888/annonces/600abc9abb7141b65e55ce4a  HTTP/1.1
content-type: application/json

###
PATCH http://localhost:8888/annonces/600abc9abb7141b65e55ce48 HTTP/1.1
content-type: application/json

[
  { "propName" : "owner", "value": "60091fdfe14a436df9c5eabb"  }
]

#     "propName" : "name", "value": "Amir"
#     "propName" : "price", "value": "1100",
#     "propName" : "image", "value": "/assets/image/2.jpg",
#     "propName" : "category", "value": "Apple",
#     "propName" : "type", "value": "Smartphone",
#     "propName" : "description", "value": ["very Excelent phone", "Awsome","Smallll"]

###
DELETE http://localhost:8888/annonces/5f9413e0d3527b0fae4f4701 HTTP/1.1
content-type: application/json

###
POST http://localhost:8888/annonces HTTP/1.1
content-type: application/json

{
  "name"       : "Ali",
  "price"      : "34",
  "image"      : "/assets/image/1.jpg",
  "category"   : "Apple",
  "type"       : "SmartWatch",
  "description": ["very Excelent phone", "Awsome","Big"]
}

###

POST http://localhost:8888/annonces
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

{
  "name"       : "Ali",
  "price"      : "34",
  "image"      : "/assets/image/1.jpeg",
  "category"   : "Apple",
  "type"       : "SmartWatch",
  "description": ["very Excelent phone", "Awsome","Big"]
}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.jpeg"
Content-Type: image/jpeg

< ./1.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###








# Lends
GET http://localhost:8888/lends/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImFkZHJlc3MiOnsibnVtYmVyIjoxMTksInN0cmVldCI6IlJVRSBEVSBGQVVCT1VSRyBCT1VUT05ORVQiLCJjaXR5IjoiTW9udHBlbGxpZXIiLCJwb3N0YWwiOjM0MDkwfSwicGhvdG8iOnsidXBsb2FkZWQiOiIyMDIxLTAxLTMwVDIyOjA3OjU2LjY1N1oifSwicm9sZSI6ImFkbWluIiwiX2lkIjoiNjAwOTFmZGZlMTRhNDM2ZGY5YzVlYWJiIiwiZmlyc3ROYW1lIjoiQW1pciIsImxhc3ROYW1lIjoiU0hJUkFMSSBQT1VSIiwicGhvbmUiOiIrMzMgNiAyOCAyOSA5MCAyMiIsImVtYWlsIjoiYW1pckBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImFtaXIiLCJwYXNzd29yZCI6IiQyYSQxMCRObVlFZkd2Z3JpTlBFRWV1a3lZQzRPMWJrRXBXb3NCZE9lU1JObXdxdGZCc1NNUTJPeGJFYSJ9LCJpYXQiOjE2MTIwNDQ0NzYsImV4cCI6MTYxMjY0OTI3Nn0.f5karr-X39Uf6GkgO24ZFAOusi5-NzZxWFTb9lTyUfo

###
GET http://localhost:8888/lends/my/ads HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImFkZHJlc3MiOnsibnVtYmVyIjoxMTksInN0cmVldCI6IjIgQXZlbnVlIGRlcyBKZXV4IE9seW1waXF1ZXMiLCJjaXR5IjoiR3Jlbm9ibGUiLCJwb3N0YWwiOjM4MTAwfSwicGhvdG8iOnsiaWQiOiI2MDE0YzY1OWE4MGJjMTEyMWJiODJmOGIiLCJ1cmwiOiIvQzpcXGZha2VwYXRoXFwzNzM4NDI4Ny5qcGciLCJ0aXRsZSI6IkFtaXItUE9VUiIsInVwbG9hZGVkIjoiMjAyMS0wMS0zMFQwMjozNzoxMy41MjZaIn0sInJvbGUiOiJ1c2VyIiwiX2lkIjoiNjAxNGM2NTlhODBiYzExMjFiYjgyZjhhIiwiZmlyc3ROYW1lIjoiQW1pciIsImxhc3ROYW1lIjoiUE9VUiIsInBob25lIjoiKzMzIDYgMjggMjkgOTAgMjIiLCJlbWFpbCI6ImFpc3NhdG91QGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiYWlzc2F0b3UiLCJwYXNzd29yZCI6IiQyYSQxMCRYNDFZUGZvWXpWSy9vdFU1ajB4clR1V3lvWVVBeGRFY2xuS0ZpcWxtVjVaMEJVdm5DYkxWNiIsIl9fdiI6MH0sImlhdCI6MTYxMTk3NDI0NSwiZXhwIjoxNjEyNTc5MDQ1fQ.aTFfJG36loPsMbIwAtiL0si2Y9Nooq_oJ9J51Ms1Dlg

###
GET http://localhost:8888/lends/6015d84f8fd59814517e07f9 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImFkZHJlc3MiOnsibnVtYmVyIjoxMTksInN0cmVldCI6IjIgQXZlbnVlIGRlcyBKZXV4IE9seW1waXF1ZXMiLCJjaXR5IjoiR3Jlbm9ibGUiLCJwb3N0YWwiOjM4MTAwfSwicGhvdG8iOnsiaWQiOiI2MDE0YzY1OWE4MGJjMTEyMWJiODJmOGIiLCJ1cmwiOiIvQzpcXGZha2VwYXRoXFwzNzM4NDI4Ny5qcGciLCJ0aXRsZSI6IkFtaXItUE9VUiIsInVwbG9hZGVkIjoiMjAyMS0wMS0zMFQwMjozNzoxMy41MjZaIn0sInJvbGUiOiJ1c2VyIiwiX2lkIjoiNjAxNGM2NTlhODBiYzExMjFiYjgyZjhhIiwiZmlyc3ROYW1lIjoiQW1pciIsImxhc3ROYW1lIjoiUE9VUiIsInBob25lIjoiKzMzIDYgMjggMjkgOTAgMjIiLCJlbWFpbCI6ImFpc3NhdG91QGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiYWlzc2F0b3UiLCJwYXNzd29yZCI6IiQyYSQxMCRYNDFZUGZvWXpWSy9vdFU1ajB4clR1V3lvWVVBeGRFY2xuS0ZpcWxtVjVaMEJVdm5DYkxWNiIsIl9fdiI6MH0sImlhdCI6MTYxMTk3NDI0NSwiZXhwIjoxNjEyNTc5MDQ1fQ.aTFfJG36loPsMbIwAtiL0si2Y9Nooq_oJ9J51Ms1Dlg


###
PATCH http://localhost:8888/lends/amir HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImFkZHJlc3MiOnsibnVtYmVyIjoxMTksInN0cmVldCI6IjIgQXZlbnVlIGRlcyBKZXV4IE9seW1waXF1ZXMiLCJjaXR5IjoiR3Jlbm9ibGUiLCJwb3N0YWwiOjM4MTAwfSwicGhvdG8iOnsiaWQiOiI2MDE0YzY1OWE4MGJjMTEyMWJiODJmOGIiLCJ1cmwiOiIvQzpcXGZha2VwYXRoXFwzNzM4NDI4Ny5qcGciLCJ0aXRsZSI6IkFtaXItUE9VUiIsInVwbG9hZGVkIjoiMjAyMS0wMS0zMFQwMjozNzoxMy41MjZaIn0sInJvbGUiOiJ1c2VyIiwiX2lkIjoiNjAxNGM2NTlhODBiYzExMjFiYjgyZjhhIiwiZmlyc3ROYW1lIjoiQW1pciIsImxhc3ROYW1lIjoiUE9VUiIsInBob25lIjoiKzMzIDYgMjggMjkgOTAgMjIiLCJlbWFpbCI6ImFpc3NhdG91QGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiYWlzc2F0b3UiLCJwYXNzd29yZCI6IiQyYSQxMCRYNDFZUGZvWXpWSy9vdFU1ajB4clR1V3lvWVVBeGRFY2xuS0ZpcWxtVjVaMEJVdm5DYkxWNiIsIl9fdiI6MH0sImlhdCI6MTYxMTk3NDI0NSwiZXhwIjoxNjEyNTc5MDQ1fQ.aTFfJG36loPsMbIwAtiL0si2Y9Nooq_oJ9J51Ms1Dlg

[
  { "propName" : "owner", "value": "60091fdfe14a436df9c5eabb"  }
]

###
DELETE http://localhost:8888/lends/6015d84f8fd59814517e07f9 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImFkZHJlc3MiOnsibnVtYmVyIjoxMTksInN0cmVldCI6IjIgQXZlbnVlIGRlcyBKZXV4IE9seW1waXF1ZXMiLCJjaXR5IjoiR3Jlbm9ibGUiLCJwb3N0YWwiOjM4MTAwfSwicGhvdG8iOnsiaWQiOiI2MDE0YzY1OWE4MGJjMTEyMWJiODJmOGIiLCJ1cmwiOiIvQzpcXGZha2VwYXRoXFwzNzM4NDI4Ny5qcGciLCJ0aXRsZSI6IkFtaXItUE9VUiIsInVwbG9hZGVkIjoiMjAyMS0wMS0zMFQwMjozNzoxMy41MjZaIn0sInJvbGUiOiJ1c2VyIiwiX2lkIjoiNjAxNGM2NTlhODBiYzExMjFiYjgyZjhhIiwiZmlyc3ROYW1lIjoiQW1pciIsImxhc3ROYW1lIjoiUE9VUiIsInBob25lIjoiKzMzIDYgMjggMjkgOTAgMjIiLCJlbWFpbCI6ImFpc3NhdG91QGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiYWlzc2F0b3UiLCJwYXNzd29yZCI6IiQyYSQxMCRYNDFZUGZvWXpWSy9vdFU1ajB4clR1V3lvWVVBeGRFY2xuS0ZpcWxtVjVaMEJVdm5DYkxWNiIsIl9fdiI6MH0sImlhdCI6MTYxMTk3NDI0NSwiZXhwIjoxNjEyNTc5MDQ1fQ.aTFfJG36loPsMbIwAtiL0si2Y9Nooq_oJ9J51Ms1Dlg

[{
  "lender" : "60091fdfe14a436df9c5eabb"
}]

###
POST http://localhost:8888/lends HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Il9pZCI6IjVmOTYyNmY0OTNjM2U1MjhmZmI5Y2M1NyIsIm5hbWUiOiJBbWlyIFNISVJBTEkgUE9VUiIsImVtYWlsIjoiZW1hc2FsYXJpQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiZW1hIiwicGFzc3dvcmQiOiIkMmEkMTAkZm51L3FUdXp6Z2hONk1GOVNDWHlYLml3QUQ5YWhGdWlPaDA5cUVDS0lQYkMyZllHZ2ZDcFMiLCJfX3YiOjB9LCJpYXQiOjE2MDM2NzU5MzYsImV4cCI6MTYwNDI4MDczNn0.Z4VnOFMXBQGrq_0_SGzIjghsOEmefVxt1WTW1DWL5mQ

{
  "quantity": "2",
  "annonce": "iPhone 12",
  "owner": "5f8e1de97f8f3d15035eff59"
}

###





# Users

GET http://localhost:8888/users/test

###


GET http://localhost:8888/users/profile HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjhjMGE4NjIxMzIyZDU4NzE2NzAxMzkiLCJuYW1lIjoiQW1pciBTSElSQUxJIFBPVVIiLCJlbWFpbCI6ImVtYXNhbGFyaUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImVtYSIsInBhc3N3b3JkIjoiJDJhJDEwJExSMm52UTgzSFFOZTFjQVNFbzVnUy5KSnA0d01GcTdxZ2NPdTBXSkt2QndQT09YOUdiQ1BhIiwiX192IjowLCJpYXQiOjE2MDMwNzgzODEsImV4cCI6MTYwMzY4MzE4MX0.fboKqI5-u8OkuBh56ulgDI1Z6gOahOVQOF5j7kh0umU

###
GET  http://localhost:8888/users/authenticate HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjhlMWRlOTdmOGYzZDE1MDM1ZWZmNTkiLCJuYW1lIjoiQW1pciIsImVtYWlsIjoiZW1hc2FsYXJpQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiYW1pciIsInBhc3N3b3JkIjoiJDJhJDEwJGJrYXdSNnBCRE5kTWlUVTRuN0UwbnUyQVdNQzB4ckMyeXVJamI4Q2htL0ZXN0Y3RWc4Tkd5IiwiX192IjowLCJpYXQiOjE2MDMxNTc1ODEsImV4cCI6MTYwMzc2MjM4MX0.fwaDnBtQozvMC_hOX540EFx-ruHZkrg1uqbE8ORoFQ4

{
  "username":"emasalari@gmail.com",
  "password":"123"
}

###
DELETE http://localhost:8888/users/5f8f972bdc12fb2c21181671 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjhlMWRlOTdmOGYzZDE1MDM1ZWZmNTkiLCJuYW1lIjoiQW1pciIsImVtYWlsIjoiZW1hc2FsYXJpQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiYW1pciIsInBhc3N3b3JkIjoiJDJhJDEwJGJrYXdSNnBCRE5kTWlUVTRuN0UwbnUyQVdNQzB4ckMyeXVJamI4Q2htL0ZXN0Y3RWc4Tkd5IiwiX192IjowLCJpYXQiOjE2MDMxNTc1ODEsImV4cCI6MTYwMzc2MjM4MX0.fwaDnBtQozvMC_hOX540EFx-ruHZkrg1uqbE8ORoFQ4

###




