version: "1"
services:
    mysql:
        image: mysql:latest
        container_name: ipsMysql
        ports:
            - "6603:3306"
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
    site:
        build: .
        container_name: su6iProject
        ports:
            - "8080:80"
        expose:
            - "80"
        depends_on:
            - mysql
        volumes:
          - .:/app